services:
  minecraft-papermc:
    tty: true  # Выделить TTY
    stdin_open: true  # Открыть STDIN
    build: .
    image: papermc
    container_name: papermc-server
    restart: unless-stopped
    environment:
      - EULA=${EULA:-FALSE}           
      - MC_VERSION=${MC_VERSION:-latest}
      - PAPER_BUILD=${PAPER_BUILD:-latest}
      - MC_RAM=${MC_RAM:-4096M}
    ports:
      - "25565:25565/tcp"             
    volumes:
      - ../data:/papermc              
    healthcheck:
      test: ["CMD-SHELL", "netstat -ln | grep 25565 || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - papermc-net

networks:                          
  papermc-net:
    driver: bridge